VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ThisWorkbook"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
'Public recordUpdate As Object
Private Sub Workbook_Open()
    'UserForm_Initialize
    'MsgBox "hello"
    'Set recordUpdate = CreateObject("Scripting.Dictionary")

    
End Sub
'Private Sub UserForm_Initialize()
'HistDataView.ListViewHist.ColumnHeaders.Add , , "日期", 40
'HistDataView.ListViewHist.ColumnHeaders.Add , , "最低价", 40
'HistDataView.ListViewHist.ColumnHeaders.Add , , "最高价", 40
'HistDataView.ListViewHist.ColumnHeaders.Add , , "极值", 120
'HistDataView.ListViewHist.ColumnHeaders.Add , , "最高价比较", 80
'HistDataView.ListViewHist.ColumnHeaders.Add , , "最低价比较", 80
'HistDataView.ListViewHist.ColumnHeaders.Add , , "差值", 80
'HistDataView.ListViewHist.View = lvwReport
'HistDataView.ListViewHist.FullRowSelect = True
'HistDataView.ListViewHist.Gridlines = True
'End Sub
