# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MinDataUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(QtWidgets.QWidget):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(1116, 685)
        self.bclj_2 = QtWidgets.QLineEdit(dialog)
        self.bclj_2.setGeometry(QtCore.QRect(490, 20, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.bclj_2.setFont(font)
        self.bclj_2.setReadOnly(True)
        self.bclj_2.setObjectName("bclj_2")
        self.groupBox = QtWidgets.QGroupBox(dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 471, 201))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_2.setGeometry(QtCore.QRect(290, 60, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.zhi = QtWidgets.QLabel(self.groupBox)
        self.zhi.setGeometry(QtCore.QRect(270, 50, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.zhi.setFont(font)
        self.zhi.setObjectName("zhi")
        self.xzdtfs = QtWidgets.QPushButton(self.groupBox)
        self.xzdtfs.setGeometry(QtCore.QRect(10, 130, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.xzdtfs.setFont(font)
        self.xzdtfs.setObjectName("xzdtfs")
        self.xzlsFs_2 = QtWidgets.QPushButton(self.groupBox)
        self.xzlsFs_2.setGeometry(QtCore.QRect(10, 100, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.xzlsFs_2.setFont(font)
        self.xzlsFs_2.setObjectName("xzlsFs_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(10, 162, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.xzlsFs_3 = QtWidgets.QPushButton(self.groupBox)
        self.xzlsFs_3.setGeometry(QtCore.QRect(10, 20, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.xzlsFs_3.setFont(font)
        self.xzlsFs_3.setObjectName("xzlsFs_3")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(110, 60, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(1999, 12, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.xzsj = QtWidgets.QLabel(self.groupBox)
        self.xzsj.setGeometry(QtCore.QRect(10, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.xzsj.setFont(font)
        self.xzsj.setObjectName("xzsj")
        self.groupBox_2 = QtWidgets.QGroupBox(dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 210, 471, 471))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.dqljwj_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.dqljwj_2.setGeometry(QtCore.QRect(10, 20, 151, 31))
        self.dqljwj_2.setObjectName("dqljwj_2")
        self.hbbb = QtWidgets.QPushButton(self.groupBox_2)
        self.hbbb.setGeometry(QtCore.QRect(290, 430, 121, 31))
        self.hbbb.setObjectName("hbbb")
        self.hbgpCode = QtWidgets.QLabel(self.groupBox_2)
        self.hbgpCode.setGeometry(QtCore.QRect(10, 420, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hbgpCode.setFont(font)
        self.hbgpCode.setObjectName("hbgpCode")
        self.gpdmHb = QtWidgets.QLineEdit(self.groupBox_2)
        self.gpdmHb.setGeometry(QtCore.QRect(90, 430, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.gpdmHb.setFont(font)
        self.gpdmHb.setObjectName("gpdmHb")
        self.listView = QtWidgets.QListView(self.groupBox_2)
        self.listView.setGeometry(QtCore.QRect(10, 60, 441, 361))
        self.listView.setObjectName("listView")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar_2.setGeometry(QtCore.QRect(170, 20, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.ljxz = QtWidgets.QPushButton(dialog)
        self.ljxz.setGeometry(QtCore.QRect(990, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ljxz.setFont(font)
        self.ljxz.setObjectName("ljxz")
        self.groupBox_3 = QtWidgets.QGroupBox(dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(490, 59, 621, 621))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.listView_2 = QtWidgets.QListView(self.groupBox_3)
        self.listView_2.setGeometry(QtCore.QRect(10, 30, 601, 571))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.listView_2.setFont(font)
        self.listView_2.setObjectName("listView_2")
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.bclj_2.raise_()
        self.ljxz.raise_()

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "股票分时交易数据提取工具"))
        self.groupBox.setTitle(_translate("dialog", "下载数据"))
        self.zhi.setText(_translate("dialog", "至"))
        self.xzdtfs.setText(_translate("dialog", "下载当天分时"))
        self.xzlsFs_2.setText(_translate("dialog", "下载历史分时"))
        self.xzlsFs_3.setText(_translate("dialog", "编辑股票代码文件"))
        self.xzsj.setText(_translate("dialog", "下载时间："))
        self.groupBox_2.setTitle(_translate("dialog", "合并数据"))
        self.dqljwj_2.setText(_translate("dialog", "查询"))
        self.hbbb.setText(_translate("dialog", "合并表格"))
        self.hbgpCode.setText(_translate("dialog", "股票代码："))
        self.ljxz.setText(_translate("dialog", "存储路径"))
        self.groupBox_3.setTitle(_translate("dialog", "信息"))

