# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MinDataUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(QtWidgets.QWidget):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(839, 665)
        self.gpdm = QtWidgets.QLabel(dialog)
        self.gpdm.setGeometry(QtCore.QRect(10, 30, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gpdm.setFont(font)
        self.gpdm.setObjectName("gpdm")
        self.gpdmEdit = QtWidgets.QLineEdit(dialog)
        self.gpdmEdit.setGeometry(QtCore.QRect(100, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.gpdmEdit.setFont(font)
        self.gpdmEdit.setObjectName("gpdmEdit")
        self.xzsj = QtWidgets.QLabel(dialog)
        self.xzsj.setGeometry(QtCore.QRect(10, 100, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.xzsj.setFont(font)
        self.xzsj.setObjectName("xzsj")
        self.dateEdit = QtWidgets.QDateEdit(dialog)
        self.dateEdit.setGeometry(QtCore.QRect(99, 110, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(1999, 12, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.bclj = QtWidgets.QLabel(dialog)
        self.bclj.setGeometry(QtCore.QRect(10, 60, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.bclj.setFont(font)
        self.bclj.setObjectName("bclj")
        self.bclj_2 = QtWidgets.QLineEdit(dialog)
        self.bclj_2.setGeometry(QtCore.QRect(100, 70, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.bclj_2.setFont(font)
        self.bclj_2.setReadOnly(True)
        self.bclj_2.setObjectName("bclj_2")
        self.xzlsFs = QtWidgets.QPushButton(dialog)
        self.xzlsFs.setGeometry(QtCore.QRect(10, 140, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.xzlsFs.setFont(font)
        self.xzlsFs.setObjectName("xzlsFs")
        self.groupBox = QtWidgets.QGroupBox(dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 471, 651))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.listView_2 = QtWidgets.QListView(self.groupBox)
        self.listView_2.setGeometry(QtCore.QRect(10, 240, 441, 401))
        self.listView_2.setObjectName("listView_2")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_2.setGeometry(QtCore.QRect(290, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.zhi = QtWidgets.QLabel(self.groupBox)
        self.zhi.setGeometry(QtCore.QRect(270, 90, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.zhi.setFont(font)
        self.zhi.setObjectName("zhi")
        self.ljxz = QtWidgets.QPushButton(self.groupBox)
        self.ljxz.setGeometry(QtCore.QRect(360, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ljxz.setFont(font)
        self.ljxz.setObjectName("ljxz")
        self.xzdtfs = QtWidgets.QPushButton(self.groupBox)
        self.xzdtfs.setGeometry(QtCore.QRect(10, 200, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.xzdtfs.setFont(font)
        self.xzdtfs.setObjectName("xzdtfs")
        self.xzlsFs_2 = QtWidgets.QPushButton(self.groupBox)
        self.xzlsFs_2.setGeometry(QtCore.QRect(10, 160, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.xzlsFs_2.setFont(font)
        self.xzlsFs_2.setObjectName("xzlsFs_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(270, 20, 171, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_2 = QtWidgets.QGroupBox(dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(470, 10, 351, 651))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.listView = QtWidgets.QListView(self.groupBox_2)
        self.listView.setGeometry(QtCore.QRect(10, 80, 331, 451))
        self.listView.setObjectName("listView")
        self.dqlj = QtWidgets.QLineEdit(self.groupBox_2)
        self.dqlj.setGeometry(QtCore.QRect(10, 20, 201, 31))
        self.dqlj.setReadOnly(True)
        self.dqlj.setObjectName("dqlj")
        self.dqljwj = QtWidgets.QPushButton(self.groupBox_2)
        self.dqljwj.setGeometry(QtCore.QRect(220, 20, 121, 31))
        self.dqljwj.setObjectName("dqljwj")
        self.hbgpCode = QtWidgets.QLabel(self.groupBox_2)
        self.hbgpCode.setGeometry(QtCore.QRect(20, 540, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.hbgpCode.setFont(font)
        self.hbgpCode.setObjectName("hbgpCode")
        self.gpdmHb = QtWidgets.QLineEdit(self.groupBox_2)
        self.gpdmHb.setGeometry(QtCore.QRect(120, 540, 113, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.gpdmHb.setFont(font)
        self.gpdmHb.setObjectName("gpdmHb")
        self.hbbb = QtWidgets.QPushButton(self.groupBox_2)
        self.hbbb.setGeometry(QtCore.QRect(240, 540, 101, 31))
        self.hbbb.setObjectName("hbbb")
        self.dqljwj_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.dqljwj_2.setGeometry(QtCore.QRect(10, 50, 331, 31))
        self.dqljwj_2.setObjectName("dqljwj_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 580, 331, 41))
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.gpdm.raise_()
        self.gpdmEdit.raise_()
        self.xzsj.raise_()
        self.dateEdit.raise_()
        self.bclj.raise_()
        self.bclj_2.raise_()
        self.xzlsFs.raise_()

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.gpdm.setText(_translate("dialog", "股票代码："))
        self.xzsj.setText(_translate("dialog", "下载时间："))
        self.bclj.setText(_translate("dialog", "保存路径："))
        self.xzlsFs.setText(_translate("dialog", "下载历史分时"))
        self.groupBox.setTitle(_translate("dialog", "下载数据"))
        self.zhi.setText(_translate("dialog", "至"))
        self.ljxz.setText(_translate("dialog", "路径选择"))
        self.xzdtfs.setText(_translate("dialog", "下载当天分时"))
        self.xzlsFs_2.setText(_translate("dialog", "多个股票下载历史分时"))
        self.groupBox_2.setTitle(_translate("dialog", "合并数据"))
        self.dqljwj.setText(_translate("dialog", "选择路径"))
        self.hbgpCode.setText(_translate("dialog", "股票代码："))
        self.hbbb.setText(_translate("dialog", "合并表格"))
        self.dqljwj_2.setText(_translate("dialog", "查询"))

