# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TdxAudTool.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(QtWidgets.QWidget):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(831, 616)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(660, 590, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.btn_lhb = QtWidgets.QPushButton(Dialog)
        self.btn_lhb.setGeometry(QtCore.QRect(217, 30, 75, 23))
        self.btn_lhb.setObjectName("btn_lhb")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 821, 291))
        self.groupBox.setObjectName("groupBox")
        self.tv_lhb = QtWidgets.QTableView(self.groupBox)
        self.tv_lhb.setGeometry(QtCore.QRect(10, 51, 801, 231))
        self.tv_lhb.setObjectName("tv_lhb")
        self.rb_5day = QtWidgets.QRadioButton(self.groupBox)
        self.rb_5day.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.rb_5day.setObjectName("rb_5day")
        self.rb_10day = QtWidgets.QRadioButton(self.groupBox)
        self.rb_10day.setGeometry(QtCore.QRect(60, 20, 47, 16))
        self.rb_10day.setObjectName("rb_10day")
        self.rb_30day = QtWidgets.QRadioButton(self.groupBox)
        self.rb_30day.setGeometry(QtCore.QRect(110, 20, 47, 16))
        self.rb_30day.setObjectName("rb_30day")
        self.rb_60day = QtWidgets.QRadioButton(self.groupBox)
        self.rb_60day.setGeometry(QtCore.QRect(160, 20, 47, 16))
        self.rb_60day.setObjectName("rb_60day")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 310, 821, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.rb_lhb = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_lhb.setGeometry(QtCore.QRect(20, 50, 89, 16))
        self.rb_lhb.setObjectName("rb_lhb")
        self.rb_all = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_all.setGeometry(QtCore.QRect(120, 50, 111, 16))
        self.rb_all.setObjectName("rb_all")
        self.btn_read_stock = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_read_stock.setGeometry(QtCore.QRect(380, 50, 251, 23))
        self.btn_read_stock.setObjectName("btn_read_stock")
        self.lv_msg = QtWidgets.QListView(self.groupBox_2)
        self.lv_msg.setGeometry(QtCore.QRect(10, 80, 801, 192))
        self.lv_msg.setObjectName("lv_msg")
        self.le_tdx_path = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_tdx_path.setGeometry(QtCore.QRect(110, 20, 141, 20))
        self.le_tdx_path.setObjectName("le_tdx_path")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label.setObjectName("label")
        self.btn_tdx_path = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_tdx_path.setGeometry(QtCore.QRect(260, 20, 75, 23))
        self.btn_tdx_path.setObjectName("btn_tdx_path")
        self.le_read_path = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_read_path.setGeometry(QtCore.QRect(460, 20, 171, 20))
        self.le_read_path.setObjectName("le_read_path")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(380, 20, 81, 16))
        self.label_2.setObjectName("label_2")
        self.btn_clearMsg = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_clearMsg.setGeometry(QtCore.QRect(730, 50, 75, 23))
        self.btn_clearMsg.setObjectName("btn_clearMsg")
        self.rb_set_stock = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_set_stock.setGeometry(QtCore.QRect(240, 50, 111, 16))
        self.rb_set_stock.setObjectName("rb_set_stock")
        self.le_outpath = QtWidgets.QLineEdit(Dialog)
        self.le_outpath.setGeometry(QtCore.QRect(90, 590, 231, 20))
        self.le_outpath.setObjectName("le_outpath")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 590, 81, 16))
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(330, 590, 261, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.buttonBox.raise_()
        self.btn_lhb.raise_()
        self.le_outpath.raise_()
        self.label_3.raise_()
        self.progressBar.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_lhb.setText(_translate("Dialog", "获取龙虎榜"))
        self.groupBox.setTitle(_translate("Dialog", "龙虎榜"))
        self.rb_5day.setText(_translate("Dialog", "5日"))
        self.rb_10day.setText(_translate("Dialog", "10日"))
        self.rb_30day.setText(_translate("Dialog", "30日"))
        self.rb_60day.setText(_translate("Dialog", "60日"))
        self.groupBox_2.setTitle(_translate("Dialog", "获取通达信数据"))
        self.rb_lhb.setText(_translate("Dialog", "路径龙虎榜股票"))
        self.rb_all.setText(_translate("Dialog", "路径下所有股票"))
        self.btn_read_stock.setText(_translate("Dialog", "从通达信读取股票数据"))
        self.label.setText(_translate("Dialog", "通达信安装路径"))
        self.btn_tdx_path.setText(_translate("Dialog", "查找"))
        self.label_2.setText(_translate("Dialog", "数据读取路径"))
        self.btn_clearMsg.setText(_translate("Dialog", "清除信息"))
        self.rb_set_stock.setText(_translate("Dialog", "路径下指定股票"))
        self.label_3.setText(_translate("Dialog", "数据输出路径"))

